package com.example.bicycleshop.backend.entities.enums;

public enum BicyclePartType {
    FRAME, FRONT_WHEEL, REAR_WHEEL, FRONT_BRAKE, REAR_BRAKE, SEAT, TIRE, RIM, SPOKE, CASSETTE, CHAIN, CRANK, PEDAL,
    REAR_DERAILLEUR, FRONT_DERAILLEUR, HANDLEBARS, FORK, BOTTLE_CAGE, REAR_RACK, FRONT_RACK, REAR_FENDER, FRONT_FENDER
}
